name: lineartetrahedron
channels:
  - conda-forge
dependencies:
  - python >=3.11,<3.14
  - numpy >=2.0
  - cmake >=3.25
  - ninja >=1.11
  - nanobind >=2.2
  - scikit-build-core >=0.10
  - libblas
  - liblapack
  - cxx-compiler
  - pip
  - matplotlib >=3.8
